### ISSUE TITLE
Doesn't always work

### ISSUE THREAD

**Issue by ayalpani** [AppWorkshop/cordova-plugin-csp-override#1]
Hi @cunneen 
Thanks for this lib, I am trying to use it but struggle to get it working. While it correctly modifies the meta tag on start of "meteor run", it fails to do so on updates I make to my code (so on the re-compiles).

Any idea what might go wrong here?
Best

**Comment by cunneen** [comment]
If you're talking about meteor hot-code reloads, I wouldn't be surprised if it gets overridden by meteor's CSP as [defined in the meteor's boilerplate](https://github.com/meteor/meteor/blob/master/packages/boilerplate-generator/template-web.cordova.js#L32); no cordova hooks will be run at all on a hot-code reload.

This is a generic (non-meteor) cordova plugin; if you want to tweak the settings from within meteor, you might want to give the [browser-policy](https://github.com/meteor/meteor/tree/master/packages/browser-policy) package a try.

Does it work from `meteor run ...` the very first time?

**Comment by ayalpani** [comment]
Hi, yes I am talking about the hot-code reloads. 

> if you want to tweak the settings from within meteor, you might want to give the browser-policy package a try.

As far as I believe to have understood the matter, the browser-policy package does not apply to meteor/cordova projects. The boilerplate code you pointed to is dominant. This is also how this section reads to me:

https://guide.meteor.com/mobile.html#csp

> For now, Meteor adds a permissive <meta http-equiv="Content-Security-Policy" content="..." header to the generated index page. We may want to allow more fine grained control in the future (through integrating with the browser-policy package for instance.)

At least browser-policies I have tried to define have no effect on the meta tag.

> Does it work from meteor run ... the very first time?

Yes it does!

If you have any idea (also for a "creative hack") how I could solve this issue, I'd appreciate your opinion.
Many thanks!

**Comment by cunneen** [comment]
The one that is sure to work is to fork meteor, and modify the `boilerplate-generator` to use a dynamic value for the CSP content rather than the hard-coded string. Please submit a PR (to meteor) if you do this!

Another way (which I'm not certain would work) would be to hook into the hot-code reload on cordova and try to clobber the CSP before it gets reloaded. I don't really know much about the internals of hot-code-reload on cordova, other than that it uses localstorage (I think). Check [this](https://forums.meteor.com/t/is-there-an-official-documentation-of-reload--onmigrate/16974) out as a starting point.

If you don't mind I'm going to close this issue; it's not something that can be fixed by a cordova plugin.

**Comment by ayalpani** [comment]
Mike, thanks for taking the time to discuss things with me. I will have to try both methods

**Comment by ayalpani** [comment]
For anyone who is interested: 

the version I chose and that works is to copy the the boilerplate-generator package to a local package-folder in my meteor project, then modify the hard coded value of the CSP meta tag and run "meteor add boilerplate-generator". Thanks again, Mike!
